language: python
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pygame
  - pip install codecov
  - pip install .
script:
  - coverage run tests
after_success:
  - codecov